### ISSUE TITLE
com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.

### ISSUE THREAD

**Issue by arunkumar-ebsco** [awslabs/amazon-kinesis-producer#115] opened 2017-06-14 18:36 UTC
Issue while using KPL 0.10.2 version.

{
	"timestamp": 1497278449000,
	"container_id": "026c0118ac6f287f07f113200560046f459688c7517a7d017997341865928a3b",
	"container_name": "/ecs-platform_shared_helloworldmiddle-family-257-platformsharedhelloworldmiddle-b4efe2b8d1c8cfc8cf01",
	"source": "stdout",
	"log": "{\"timeMillis\":1497278449773,\"thread\":\"pool-5-thread-1\",\"level\":\"ERROR\",\"loggerName\":\"com.ebsco.txnlogging.TransactionProcessor\",\"message\":\"com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.\\n\\tat com.amazonaws.services.kinesis.producer.Daemon.add(Daemon.java:171)\\n\\tat com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:467)\\n\\tat com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:338)\\n\\tat com.ebsco.txnlogging.TransactionProcessor.run(TransactionProcessor.java:74)\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\\n\\tat java.lang.Thread.run(Thread.java:745)\\n\",\"endOfBatch\":false,\"loggerFqcn\":\"org.apache.logging.slf4j.Log4jLogger\",\"contextMap\":{\"market\":\"market\",\"subenv\":\"subenv\",\"environment\":\"environment\",\"domain\":\"domain\",\"applicationId\":\"helloworldmiddleservice\",\"containerId\":\"026c0118ac6f\"},\"threadId\":29,\"threadPriority\":5}\r"
}

**Comment by arunkumar-ebsco** [comment] 2017-06-19 00:45
This issue is happening with KPL version: 0.9.0 and 0.12.5.

**Comment by seratch** [comment] 2017-09-11 15:32
We also occasionally encounter this problem with 0.10.2. Hopefully, it will be fixed soon.

**Comment by amithgeorge** [comment] 2017-09-19 06:02
What is the behaviour you are seeing? I noticed the error for the time yesterday and it happened 5 times over a 10 minute window. The KPL process seems to get restarted on its own. Can someone confirm it? I am using 0.12.5. Btw, the issue was reported earlier as well - https://github.com/awslabs/amazon-kinesis-producer/issues/39 It is still unresolved.

**Comment by linksach3** [comment] 2018-07-02 09:47
Im seeing this issue as well. I am using KPL 0.12.8

**Comment by sheaney** [comment] 2018-10-18 14:08
I'm seeing it also with 0.12.8

**Comment by ilgo** [comment] 2019-07-03 07:47
i'm seeing this with KPL 0.12.11  
------------------------------------------------------
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>amazon-kinesis-producer</artifactId>
            <version>0.12.11</version>
        </dependency>

**Comment by cgpassante** [comment] 2019-07-24 16:02
I was seeing this issue while running in docker and AWS tech support helped me to debug it. The daemon start will fail if credentials are missing or incorrect. If you are using the java API you can inspect the return value from the future to look for detailed error messages for failed addUserRecord. Hope that helps.

**Comment by namedgraph** [comment] 2019-08-12 08:03
@cgpassante to add a callback you need a result of `addUserRecord()`. The code never reaches past it because of the exception.
#39 is the same issue. I haven't seen a solution, so I will be dropping KPL and using plain KCL, which worked.

**Comment by petermardyrosian** [comment] 2019-09-04 13:32
Hi. I have also the same issue. When will you look into it? The KPL is useless with this bug.
Caused by: com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.
	at com.amazonaws.services.kinesis.producer.Daemon.add(Daemon.java:176)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:536)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:349)

**Comment by Cory-Bradshaw** [comment] 2019-10-09 22:25
This is a duplicate of: https://github.com/awslabs/amazon-kinesis-producer/issues/39

Repeating from other issue report:

> 
> Hello,
> 
> Thank you everyone for sharing your experience and learning with the community. For an example of how to implement this, see the KPL sample application in this repository, specifically this line. (this is for a test application, and in this case, it just shuts down the sample application after displaying the underlying failure)
> 
> This is a general failure condition that occurs when there is any unresolvable configuration problem with the KPL. Usually when this happens it is for one for the following reasons:
> 
> Credentials could not be found
> Lack of permissions for resources
> Stream does not exist
> Targeting wrong region (leading to Stream does not exist)

> If you are experiencing this problem and can confirm that it is not due to a configuration/access, please re-open the issue and provide more details on your configuration and if any reproduction steps are consistently successful, including steps about stream creation, iam users/roles/permissions, container/ec2 instance, etc.
> 
> For additional assistance, you may also open a customer support ticket through the AWS console to receive more specific support.

> 
> Additionally, this can happen if the KPL process gets overwhelmed by a lack of backpressure successfully implemented by the customer. I highly recommend reading this blog post to understand some of the considerations for how to configure and use the KPL: 
> 
> https://aws.amazon.com/blogs/big-data/implementing-efficient-and-reliable-producers-with-the-amazon-kinesis-producer-library/

**Closed by Cory-Bradshaw** 2019-10-09 22:25 UTC

**Comment by kliu5598** [comment] 2022-09-14 10:13
Im seeing this issue as well. I am using KPL 0.12.9
